Implement /credits
academic-relations/ar-007-students pull request #26
Opened 2024-10-14 17:13 UTC by malloc3141

# 요약 \*

It closes #19 

피그마: https://www.figma.com/design/PpSN8r1RC76W0cfSGi1tMD/ar-007-Students?node-id=402-3332&node-type=frame&t=1fQCyofCNNSvJ9zV-0
구현하면서 생긴 디자인 관련 의견은 피그마 페이지에 달아두었습니다.

구현된 사항
- credits 페이지
- font type이랑 weight 필요한 거 추가(fonts.ts)
- 스팍스 컬러 상수 colors.ts에 추가
- footer에서 만든 사람들 누르면 /credits로 이동

확인해야 할 사항
- 디자인 상 BreadCrumb이 없는데 실제 페이지에도 필요 없는건지

# 스크린샷

![](https://github.com/user-attachments/assets/050284d9-fd57-416f-8bd4-c952ae566275)

# 이후 Task \*

- 없음

2024-10-27 07:33 UTC, wjeongchoi commented
디자인 수정되고 한번에 리뷰할게요

2025-02-26 13:58 UTC, malloc3141 commented
320~719px 디자인 수정까지 완료

2025-02-28 04:14 UTC, ChaeyeonAhn requested changes
디자인 상에서는 카드가 그림자가 없고 보더가 있습니다.
이 부분 확인해주시면 감사하겠습니다아

<img width="755" alt="스크린샷 2025-02-28 오후 1 13 27" src="https://github.com/user-attachments/assets/984309c7-ff13-427a-bff1-f55a6ad8ce6c" />

2025-03-01 06:53 UTC, ChaeyeonAhn approved these changes
굿굿 얘도 머지합시다 👍 👍 👍

2025-03-01 06:54 UTC, merged